[WIP] Hahnbee/min 1328 Reflect getStaticProps/Paths set-up on domain
mintlify/mint pull request #115
Opened 2022-12-23 17:23 UTC by hahnbeelee

# Summary

# Test Plan

2022-12-27 00:55 UTC, hanywang2 requested changes
- No description
- Auto-generated title

<img width="1624" alt="Screen Shot 2022-12-26 at 4 55 30 PM" src="https://user-images.githubusercontent.com/44352119/209594294-a803d70c-667e-4320-919b-94af92b8d64e.png">

2022-12-27 01:02 UTC, hahnbeelee commented on client/src/utils/mdx/remark/withRefactorLegacyIconFunction.ts
> +// TODO - remove this once we change everybody's format
This refactors something like `icon("house")` to become our new icon format

2022-12-27 01:06 UTC, hahnbeelee commented on client/src/ui/MDXContentController/PageHeader.tsx
> +          {subdomain && <UserFeedback />}
And because UserFeedback references our backend. We can totally make this work by:
- refactoring the feedback system to not reference our backend anymore
- architecting a solution for this referencing either environment variables or a property inside the mint config

Definitely low on the priority list though.

2022-12-27 01:08 UTC, hahnbeelee commented on client/src/ui/Header.tsx
> +              {subdomain && (
This would require some refactoring to the component because the component has logic that throws a breaking error when it's missing the subdomain. We could revisit this right before shipping the CLI because once that's shipped then people will actually see it.

2022-12-27 01:09 UTC, hahnbeelee commented on client/src/ui/Header.tsx
> +                {subdomain && (
Ditto to my last reply

2022-12-27 01:23 UTC, hanywang2 approved these changes
han-happi

2022-12-27 01:47 UTC, tobias-mintlify approved these changes

2022-12-27 01:47 UTC, tobias-mintlify commented on client/src/middleware.ts
> +  if (hostname === 'localhost:3000' || hostname === 'platformize.vercel.app') {
platformize.vercel.app is not necessary

2022-12-27 01:47 UTC, tobias-mintlify commented on client/src/pages/[[...slug]].tsx
> +          '🚧 A parsing error occured. Please contact the owner of this website. They can use the Mintlify CLI to test this website locally and see the errors that occur.',
Remove everything after "A parsing error occured." We shortened this a few weeks ago.

2022-12-27 01:47 UTC, tobias-mintlify commented on client/src/ui/MDXContentController/PageHeader.tsx
> +          {subdomain && <UserFeedback />}
Can we add `// TO DO:` comments in these places we want to refactor later? Might even be worth linking to a GitHub issue so we can track the places we need to fix.

2022-12-27 01:47 UTC, tobias-mintlify commented on client/src/ui/search/Search.tsx
> +    // TODO: Make search work in single-tenant
If we make a GitHub issue, add the link there too

2022-12-27 01:47 UTC, tobias-mintlify commented on client/src/utils/mdx/remark/withRefactorLegacyIconFunction.ts
> +// TODO - remove this once we deprecate legacy format i.e. icon("house")
What if we remove it here, so when users see the issue in the CLI they are encouraged to use the new syntax?

2022-12-27 01:51 UTC, hahnbeelee commented on client/src/utils/mdx/remark/withRefactorLegacyIconFunction.ts
> +// TODO - remove this once we deprecate legacy format i.e. icon("house")
I feel like that's kinda poor UX. The better solution here is for us to be proactive and make PR's for everyone whose still using this syntax (probably not more than like 5 people...)

2022-12-28 03:38 UTC, hahnbeelee commented on client/src/utils/mdx/remark/withRefactorLegacyIconFunction.ts
> +// TODO - remove this once we deprecate legacy format i.e. icon("house")
Removed. I'll make PRs for the ones that are affected after the CLI release

2022-12-28 04:03 UTC, merged