Build mint into a Docker image
mintlify/mint pull request #127
Opened 2023-01-05 22:01 UTC by tobias-mintlify

# Summary

Builds `mint` into a Docker image for the CLI to consume.

# Test Plan

2023-01-10 23:42 UTC, hahnbeelee requested changes

2023-01-10 23:42 UTC, hahnbeelee commented on DOCKER_README.md
> +`docker build -t mint .`
Where do I run this? In my terminal or inside Docker Desktop? After I downloaded Docker Desktop and tried running this in my terminal I got the error message "zsh: command not found: docker". I know this all seems trivial but coming from no Docker experience I'd appreciate more instruction :bongo-pray:

2023-01-10 23:43 UTC, tobias-mintlify commented on DOCKER_README.md
> +`docker build -t mint .`
Ah yea! You have to run this in the terminal while Docker Desktop is open.

2023-01-10 23:49 UTC, hahnbeelee commented on DOCKER_README.md
> +`docker build -t mint .`
Note I downloaded docker desktop and then I had to close my terminal in order to access the docker command. Might be helpful to note that for future devs.

2023-01-10 23:50 UTC, hahnbeelee commented on DOCKER_README.md
> +`docker build -t mint .`
Is the only step ensuring `docker build -t mint .` works? Are there other things I should test?

2023-01-10 23:51 UTC, hahnbeelee commented
Cool I see my mint image! (why is it 5GB 👁️ )
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/55263191/211686244-47155f44-8483-4ccf-8e4b-e5cc7bf6f886.png">

2023-01-10 23:55 UTC, tobias-mintlify commented
Node's Docker image is roughly 1Gb. Most of the rest comes from dependencies.

2023-01-11 00:11 UTC, hahnbeelee approved these changes
wasn't able to review in depth but I am in a rush to get this out the door :sad-bufo-vibe: @tobias-mintlify I might make comments in the future about things on this PR post-merge.

2023-01-11 00:13 UTC, merged