[WIP] Scrape website logo
mintlify/mint pull request #144
Opened 2023-01-08 05:04 UTC by benjamin-shen

## Summary
- Cleaned up some of the scraper function types
- Renamed navigation types and moved them to global scope
- Fixed `--overwrite` flags for images
- Scrape website logo
- Refactored some download image code

## Test Plan
The CLI should install logos to `images/logo/logo-light-mode.<ext>` for each supported doc framework. The `--overwrite` flag should work as well. I tested it on
- https://docusaurus.io/docs
- https://docs.gitbook.com
- https://docs.readme.com/main/docs/intro-to-readme

2023-01-08 15:11 UTC, tobias-mintlify requested changes
Great work! I commented a few nits

2023-01-08 15:11 UTC, tobias-mintlify commented on packages/mintlify/src/downloadImage.ts
> +    console.error("Invalid image path " + imageHref);
We should separate validation for getFileExtension from checking if the file extension is valid. Invalid file extensions should have a descriptive error message: "We do not support the file extension: EXTENSION".

Please also add a siren emoji to the start of the error messages: 🚨

2023-01-08 15:11 UTC, tobias-mintlify commented on packages/mintlify/src/scraping/site-scrapers/scrapeGitBookSection.ts
> +  const logoSrc = $("img").first().attr("src");
In case there are other `img` tags before the logo in the future, could we use this instead:

`$('div[data-testid="public.headerHomeLink"] img').first().attr("src")`

2023-01-08 15:11 UTC, tobias-mintlify commented on packages/mintlify/src/scraping/site-scrapers/scrapeDocusaurusSection.ts
> +  const logoSrc = $(".navbar__logo").children().first().attr("src");
Instead of `children().first()` you can likely use `$(".navbar__logo img").first()`

2023-01-08 15:11 UTC, tobias-mintlify commented on packages/mintlify/src/downloadImage.ts
> +    console.error("Invalid image path " + imageHref);
By the way, we need to block downloads of images over 5Mb. If you can think of a fast way to add that check to this function please do so. :)

2023-01-08 15:11 UTC, tobias-mintlify commented on packages/mintlify/src/scraping/downloadLogoImage.ts
> +  const imagePath = path.join(imageBaseDir, "logo", "logo-light-mode." + ext);
Nice!

2023-01-13 04:52 UTC, benjamin-shen commented on packages/mintlify/src/downloadImage.ts
> +    console.error("Invalid image path " + imageHref);
I researched a bit and didn't find a good way. We would probably need to download the image at least once, and then from there we could determine whether or not to save it (and possibly cache this information in a local file).

2023-01-13 04:53 UTC, benjamin-shen commented on packages/mintlify/src/scraping/site-scrapers/scrapeGitBookSection.ts
> +  const logoSrc = $("img").first().attr("src");
Thanks for all the cheerio suggestions!

2023-01-13 18:16 UTC, tobias-mintlify approved these changes
Thank you for all the improvements you made alongside this ticket. :)

2023-01-13 18:23 UTC, merged