Download from a release tag
mintlify/mint pull request #182
Opened 2023-01-15 21:24 UTC by tobias-mintlify

## Summary

Downloads GitHub repo as a tar file from the GitHub rest API instead of relying on users having Git installed locally.

This allows us to choose when we publish `mint` versions instead of always pulling from main.

## Test Plan

Ran locally using the `v.0.0.1` release.

You should be able to install and run this without changing anything in your `.mintlify` folder. We automatically delete the contents when the version changes. For testing, try changing the version in `mint-version.txt`, deleting the `client` folder, and running without internet.

2023-01-15 21:41 UTC, benjamin-shen commented
Thoughts on using a hidden file for `mint-version.txt`? Maybe `.mintrc` or `.mint`?

2023-01-16 00:21 UTC, tobias-mintlify commented
The folder `.mintlify` is already hidden.

2023-01-16 19:05 UTC, tobias-mintlify commented
Note this PR doesn't publish the CLI. We will bump and publish in a separate PR.

2023-01-17 00:42 UTC, hanywang2 reviewed
Delete some comments. There's way too much

2023-01-17 00:42 UTC, hanywang2 commented on packages/mintlify/src/local-preview/index.ts
> +      // Move extracted contents to CLIENT_PATH
Way too many comments. There's more comments in this particular function than lines of code.

If the comments just describe what the code is doing, delete it. It should only be used to supplement with context

2023-01-17 00:44 UTC, hanywang2 commented on packages/mintlify/src/local-preview/index.ts
> +      // Move extracted contents to CLIENT_PATH
https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/

2023-01-17 02:37 UTC, hahnbeelee requested changes
Please update the messages! And ditto to what Han said, too many comments

2023-01-17 02:37 UTC, hahnbeelee commented on packages/mintlify/src/local-preview/index.ts
> +      logger.text = "Downloading Mint...";
The goal of the CLI isn't to let people know about the existence of mint. In fact we are purposefully trying to make mint accessible in a way in which you don't have to know about it.
```suggestion
      logger.text = "Downloading packages...";
```

2023-01-17 02:37 UTC, hahnbeelee commented on packages/mintlify/src/local-preview/index.ts
> +      logger.text = "Extracting Mint...";
```suggestion
      logger.text = "Extracting packages...";
```

2023-01-17 03:03 UTC, hahnbeelee approved these changes

2023-01-17 03:58 UTC, merged