Wrap decodeURI in try-catch
mintlify/mint pull request #184
Opened 2023-01-15 22:40 UTC by tobias-mintlify

decodeURI can throw if the URL is invalid. This has never happened to a customer but we are wrapping it anyway to prevent client-side exceptions we know can occur.

2023-01-16 23:24 UTC, hanywang2 commented on client/src/utils/api.ts
> +      base: '',
Idk if it'll work if path and base is empty. It'll likely throw an error down the line or make some weird UI

2023-01-16 23:40 UTC, tobias-mintlify commented on client/src/utils/api.ts
> +      base: '',
The API call would fail, but it'd fail in the /api/ endpoint we use to send API requests which prevents the client-side exception

2023-01-17 00:17 UTC, hahnbeelee requested changes
You probably weren't expecting this but lets see some better practices :)))

2023-01-17 00:17 UTC, hahnbeelee commented on client/src/utils/api.ts
> +      base: '',
This doesn't seem like best practice. I haven't put a lot of thought into what would be best for this, but the expectation for functions should be that 
1. It takes in valid input (try to get the function inputs to be as consistent as possible)
2. Only return `null`/falsy values if it's an actual value
3. Throw errors otherwise

2023-01-17 02:05 UTC, hahnbeelee approved these changes

2023-01-17 02:18 UTC, merged