Use child_process.spawn for dev-watch
mintlify/mint pull request #192
Opened 2023-01-17 21:43 UTC by hahnbeelee

## Summary
Apparently using `spawn` is better for terminating ports properly than `exec` ([stackoverflow](https://stackoverflow.com/questions/20187184/how-to-kill-childprocess-in-nodejs)).

## Test Plan
1. Run `mintlify dev`
2. Terminate it
3. Run `lsof -i:3000`. There should be no node processes running. I think it's ok if the Google runs are running.
![image](https://user-images.githubusercontent.com/55263191/213018688-4e248514-7e65-4678-b4bc-7383dd6dcf65.png)

2023-01-17 21:59 UTC, tobias-mintlify requested changes

2023-01-17 21:59 UTC, tobias-mintlify commented on packages/mintlify/src/local-preview/index.ts
> +    if (output.startsWith("> Ready on http://localhost:")) {
Can we move these logs into here so they only show when the site is ready?

```
console.log(
    `🌿 ${Chalk.green(
      `Your local preview is available at http://localhost:${port}`
    )}`
  );
  console.log(
    `🌿 ${Chalk.green("Press Ctrl+C any time to stop the local preview.")}`
  );
```

2023-01-17 21:59 UTC, tobias-mintlify commented on packages/mintlify/src/local-preview/index.ts
> +    if (output.startsWith("> Ready on http://localhost:")) {
Also change `logger.succeed("Local Mintlify instance started.");` above to `Local Mintlify instance is ready. Launching your site now.`

And `Starting a local Mintlify instance...` to `Preparing local Mintlify instance.`

2023-01-18 22:08 UTC, benjamin-shen approved these changes

2023-01-18 22:08 UTC, benjamin-shen commented on packages/mintlify/src/local-preview/index.ts
> +    if (output.startsWith("> Ready on http://localhost:")) {
This is kind of a sus check, is there some env variable or something we could check instead?

2023-01-18 22:12 UTC, hahnbeelee commented on packages/mintlify/src/local-preview/index.ts
> +    if (output.startsWith("> Ready on http://localhost:")) {
Oo maybe `lsof -i:3000` and check if it's running?

2023-01-18 22:14 UTC, tobias-mintlify approved these changes

2023-01-18 22:14 UTC, merged