Restructure to guides format
mintlify/mint pull request #217
Opened 2023-01-20 03:52 UTC by tobias-mintlify

## Summary

Moves the component docs into their own anchor. I will further update our docs in a future PR so the main docs page is exclusively guides and all reference content lives inside an anchor.

Using RequestExample will hide the code blocks on mobile so I won't merge this in until can add mobile support tomorrow.

## Test Plan

Use `mintlify dev` to preview the changes locally.

2023-01-20 07:30 UTC, hahnbeelee commented
> I will further update our docs in a future PR so the main docs page is exclusively guides and all reference content lives inside an anchor.

What else do you think will need to be moved?

2023-01-20 18:00 UTC, tobias-mintlify commented
@hahnbeelee some of the API docs can be cleaned up. We introduce "Param", "ResponseExample", and others alongside the basic concept of an API playground. It would be nice to have guides with clear examples and a link to a separate section with all the components.

2023-01-21 02:48 UTC, hahnbeelee commented
@tobias-mintlify brilliant

2023-01-21 03:07 UTC, hahnbeelee commented on docs/components/overview.mdx
>  ## Examples
If you scroll down there's this section. I feel like you should mention the component reference again here
<img width="763" alt="image" src="https://user-images.githubusercontent.com/55263191/213841009-3e42a07e-0d06-427d-8906-d630f72919e3.png">

2023-01-21 03:14 UTC, hanywang2 commented on docs/mint.json
> +      "url": "components-reference"
Could we name the folder `components`? seems cleaner

2023-01-21 03:15 UTC, hahnbeelee requested changes
Can you make the 1 change i requested above?

Overall I think the components anchor looks great! I know this is just the first iteration so I would love to see more references to the components anchor from the main anchor because even if it's great if no one can find it it loses value.

2023-01-21 04:15 UTC, hahnbeelee requested changes
We need at least 1 reference to the api components from the api playground section in the main section of the docs

2023-01-21 04:28 UTC, hahnbeelee approved these changes

2023-01-21 04:30 UTC, merged