Scrape pages and sections from Intercom help center
mintlify/mint pull request #284
Opened 2023-01-29 18:49 UTC by Graviis

## Summary

## Test Plan

2023-01-29 19:24 UTC, tobias-mintlify requested changes

2023-01-29 19:24 UTC, tobias-mintlify commented on packages/mintlify/src/scraping/detectFramework.ts
> +  const isIntercom = $("meta[name=intercom:trackingEvent]").length > 0;
I think you need quotes inside this, eg: `'meta[name="intercom:trackingEvent"]'`

I can't test until later today though so feel free to comment if this is working

2023-01-29 19:24 UTC, tobias-mintlify commented on packages/mintlify/src/downloadImage.ts
>    if (!SUPPORTED_MEDIA_EXTENSIONS.includes(ext)) {
Could we add an optional boolean parameter to this function that asks `validateImageExtensions`? Then the Intercom code can pass `false` when downloading all images and bypass this if-statement.

Also, we should pass `modifyFileName` when downloading images? We should split by `/` and only take the last part of the string. See GitBook's `scrapeGitBookPage` code for how its done there.

2023-01-29 19:33 UTC, Graviis commented on packages/mintlify/src/downloadImage.ts
>    if (!SUPPORTED_MEDIA_EXTENSIONS.includes(ext)) {
yes, that will do!

2023-01-30 08:49 UTC, Graviis commented on packages/mintlify/src/scraping/detectFramework.ts
> +  const isIntercom = $("meta[name=intercom:trackingEvent]").length > 0;
it's working but im gonna add the quotes anyway

2023-01-30 09:30 UTC, Graviis commented on packages/mintlify/src/downloadImage.ts
>    if (!SUPPORTED_MEDIA_EXTENSIONS.includes(ext)) {
About this:
> Also, we should pass modifyFileName when downloading images? We should split by / and only take the last part of the string. See GitBook's scrapeGitBookPage code for how its done there.

Right now, without any modifications we are getting the last part of the string, so i think we are fine.

2023-01-30 09:35 UTC, Graviis commented on packages/mintlify/src/scraping/site-scrapers/Intercom/scrapeIntercomSection.ts
> +    });
@tobias-mintlify  I have seen that for Docusaurus and Gitbook you do this in a separated function. do you think i should do the same for Intercom?

2023-01-30 16:59 UTC, tobias-mintlify commented on packages/mintlify/src/scraping/site-scrapers/Intercom/scrapeIntercomSection.ts
> +    });
You can keep it the way you have it. Docusaurus and Gitbook have a function because we reuse the code. I'll test the PR today thoroughly later today. :)

2023-01-30 17:00 UTC, tobias-mintlify commented on packages/mintlify/src/downloadImage.ts
>    if (!SUPPORTED_MEDIA_EXTENSIONS.includes(ext)) {
Do you know if these are always `jpeg` images? It would be good to add `.jpeg` to the end of it if so. Most users would not know how to open the images otherwise.

2023-01-30 17:35 UTC, tobias-mintlify approved these changes
Works great! While testing I noticed an improvement we can make elsewhere in the CLI:

Downloading images some times crashes if there are a lot of network calls made in parallel. Here's the error I got:

```
AxiosError: Client network socket disconnected before secure TLS connection was established
    at AxiosError.from 

... stack trace ...

    code: 'ECONNRESET',
    path: null,
    host: 'downloads.intercomcdn.com',
    port: 443,
    localAddress: undefined
  }
}
```

Maybe we could try-catch image downloading and log a friendlier error message when the error code is ECONNRESET? We could say `We encountered a network error trying to download from ${imagePath} please run scrape-section again.`

2023-01-30 17:35 UTC, tobias-mintlify commented on packages/mintlify/src/scraping/site-scrapers/Intercom/scrapeIntercomSection.ts
> +        "/docs"
You don't need `/docs` here, that's used when all pages have a `/docs` directory at the start of the URL.

2023-01-30 17:36 UTC, merged

2023-01-30 18:04 UTC, hahnbeelee commented
@Graviis Can you add intercom as one of the frameworks in `packages/mintlify/scrapers.md`? And add any other relevant documentation where applicable?

2023-01-30 18:23 UTC, Graviis commented
> @Graviis Can you add intercom as one of the frameworks in `packages/mintlify/scrapers.md`? And add any other relevant documentation where applicable?

Sure!

2023-01-30 18:25 UTC, Graviis commented
> Works great! While testing I noticed an improvement we can make elsewhere in the CLI:
> 
> Downloading images some times crashes if there are a lot of network calls made in parallel. Here's the error I got:
> 
> ```
> AxiosError: Client network socket disconnected before secure TLS connection was established
>     at AxiosError.from 
> 
> ... stack trace ...
> 
>     code: 'ECONNRESET',
>     path: null,
>     host: 'downloads.intercomcdn.com',
>     port: 443,
>     localAddress: undefined
>   }
> }
> ```
> 
> Maybe we could try-catch image downloading and log a friendlier error message when the error code is ECONNRESET? We could say `We encountered a network error trying to download from ${imagePath} please run scrape-section again.`

Another solution could be open a browser and go through the pages instead of doing so many "unnatural" requests to the site