Autogenerate meta images
mintlify/mint pull request #297
Opened 2023-01-30 23:01 UTC by tobias-mintlify

Generates images using an API endpoint.

2023-01-30 23:13 UTC, hahnbeelee requested changes
Can you also add a screenshot of how this looks like?

2023-01-30 23:13 UTC, hahnbeelee commented on client/src/pages/api/og.tsx
> +    const siteLogo = subdomain
Is there a way for us to check whether this image exists other than crashing?

2023-01-30 23:13 UTC, hahnbeelee commented on client/src/pages/api/og.tsx
> +/* Disabled warning about using <img> instead of <Image> because this is an API route */
What happens when you use Image?

2023-01-30 23:13 UTC, hahnbeelee commented on client/src/layouts/SupremePageLayout.tsx
> +  const imageEndpoint = new URL(`${origin || 'https://mintlify.com/docs'}/api/og`);
Will `origin` still work for docs hosted in a subpath? for example pelm exists at pelm.com/docs will `/docs` be appended?

2023-01-30 23:13 UTC, hahnbeelee commented on client/src/layouts/SupremePageLayout.tsx
> +  const imageEndpoint = new URL(`${origin || 'https://mintlify.com/docs'}/api/og`);
We should do some error handling for this because `new URL()` will throw if the URL is not a valid URL.

2023-01-30 23:13 UTC, hahnbeelee commented on client/src/layouts/SupremePageLayout.tsx
> +  );
Set `pageMetadata.title || pageMetadata.sidebarTitle || slugToTitle(pageMetadata.href || '')` to a const and check if it exists before appending it.

2023-01-30 23:13 UTC, hahnbeelee commented on client/src/layouts/SupremePageLayout.tsx
> +  const metaTagsDict = getAllMetaTags(pageMetadata, mintConfig, imageEndpoint.toString());
Check this out - Ben sent it to me a couple days ago lmao. I think it'll help make this code more bulletproof

https://youtube.com/shorts/ps7EkRaRMzs?feature=share

2023-01-30 23:13 UTC, hahnbeelee commented on client/src/utils/getAllMetaTags.ts
> +    'twitter:image': imageEndpoint,
Are there other ones we should be adding this for?

2023-01-30 23:15 UTC, hahnbeelee commented
Can you also update the unit tests? / Look into that, they seem to be failing.

2023-01-31 01:22 UTC, tobias-mintlify commented on client/src/layouts/SupremePageLayout.tsx
> +  const metaTagsDict = getAllMetaTags(pageMetadata, mintConfig, imageEndpoint.toString());
I'll use `set` instead of `append`, but that video is recommending to use URL like this code does haha

2023-01-31 01:24 UTC, tobias-mintlify commented on client/src/layouts/SupremePageLayout.tsx
> +  );
`slugToTitle(pageMetadata.href || '')` will return an empty string in the extreme case `pageMetadata.href` is not set and all other titles are not available

2023-01-31 01:27 UTC, tobias-mintlify commented on client/src/utils/getAllMetaTags.ts
> +    'twitter:image': imageEndpoint,
Not as far as brief googling suggests: https://css-tricks.com/essential-meta-tags-social-media/#aa-final-markup

2023-01-31 01:28 UTC, tobias-mintlify commented on client/src/layouts/SupremePageLayout.tsx
> +  const imageEndpoint = new URL(`${origin || 'https://mintlify.com/docs'}/api/og`);
We want this to throw an error because that would happen when `origin` is initialized to something other than an empty string, in which case this code is wrong and needs to be updated before deploying.

2023-01-31 01:28 UTC, tobias-mintlify commented on client/src/layouts/SupremePageLayout.tsx
> +  const imageEndpoint = new URL(`${origin || 'https://mintlify.com/docs'}/api/og`);
`/docs` is not appended to the origin. That's part of the hardcoded Mintlify endpoint we fallback to.

2023-01-31 01:29 UTC, tobias-mintlify commented on client/src/pages/api/og.tsx
> +/* Disabled warning about using <img> instead of <Image> because this is an API route */
I didn't try. I don't see a reason to because Next.js images are help with loading images after the site is loaded and/or to compress them but that doesn't exist in an api route.

2023-01-31 01:30 UTC, tobias-mintlify commented
@hahnbeelee Han is taking over this PR, description is intentionally left vague because this is not ready to merge yet. I should have written that in the description to begin with, sorry!

2023-01-31 01:31 UTC, tobias-mintlify commented on client/src/pages/api/og.tsx
> +    const siteLogo = subdomain
We might be able to make a `HEAD` request.

@hanywang2 please look into this when improve this endpoint

2023-02-04 02:35 UTC, benjamin-shen commented on client/src/pages/api/og.tsx
> +/* Disabled warning about using <img> instead of <Image> because this is an API route */
Would it hurt? I'd rather stay consistent and minimize `eslint-disable`s if possible

2023-02-04 04:27 UTC, tobias-mintlify commented on client/src/pages/api/og.tsx
> +/* Disabled warning about using <img> instead of <Image> because this is an API route */
Even if it compiles I don't want to risk the unexpected behaviour. We want to send an `<img>` tag so that's what we should be writing.

2023-02-04 05:33 UTC, hanywang2 commented on client/src/pages/api/og.tsx
> +    const siteLogo = subdomain
This has been fixed by simply passing in the values of the image URIs directly

2023-02-04 06:23 UTC, benjamin-shen reviewed
IT'S BEAUTIFUL 💯

2023-02-04 06:23 UTC, benjamin-shen commented on client/src/pages/api/og.tsx
> +    const isDarkMode = Boolean(isDark);
This will make any truthy value of `isDark`, such as `isDark=false`, result in `isDarkMode=true`. Maybe you should use this?
```suggestion
    const isDarkMode = isDark === "true";
```

2023-02-04 06:23 UTC, benjamin-shen commented on client/src/pages/api/og.tsx
> +    const backgroundColor = isDarkMode ? '#0F1116' : '#FFF';
Do we want to use the user-defined background colors? Otherwise I'm worried that the other user-defined colors would clash or not be seen.

2023-02-04 06:23 UTC, benjamin-shen commented on client/src/pages/api/og.tsx
> +            width: '100%',
Is this necessary? Usually div width is 100% by default and [undesirable](https://www.impressivewebs.com/width-100-percent-css/)

2023-02-04 06:23 UTC, benjamin-shen commented on client/src/pages/api/og.tsx
> +              xmlns="http://www.w3.org/2000/svg"
What does this do?

2023-02-04 17:59 UTC, tobias-mintlify commented on client/src/pages/api/og.tsx
> +              xmlns="http://www.w3.org/2000/svg"
XML Namespaces define the SVG version you are using. It's only valid SVG if you include it. I doubt it'll impact rendering but this is a technically correct way to write the SVG.

2023-02-04 18:02 UTC, tobias-mintlify commented on client/src/utils/getOGImageEndpoint.ts
> +    setQueryParamIfExists('leftGradientColor', mintConfig.colors?.primary);
You're already passing `primary` and `light`. Move this logic to the API endpoint.

2023-02-04 18:02 UTC, tobias-mintlify commented on client/src/utils/getOGImageEndpoint.ts
> +  setQueryParamIfExists('leftGradientColor', mintConfig.colors?.dark);
Same here, no need to pass this.

2023-02-05 02:16 UTC, hanywang2 commented on client/src/pages/api/og.tsx
> +    const backgroundColor = isDarkMode ? '#0F1116' : '#FFF';
Fair enough!

2023-02-05 02:27 UTC, hanywang2 commented on client/src/pages/api/og.tsx
> +            width: '100%',
Unfortunately in this case it is

2023-02-05 03:43 UTC, hanywang2 approved these changes

2023-02-06 02:11 UTC, hahnbeelee requested changes
Hm when I navigate to http://mintlify.localhost:3000/quickstart I get this error. Note I already tried running `yarn`
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/55263191/216866781-a69693b7-68f7-4a69-933b-ca55fdc50dc9.png">

2023-02-06 06:19 UTC, hahnbeelee reviewed
Extremely long titles move the logo up and the description down
![image](https://user-images.githubusercontent.com/55263191/216897548-97058170-d234-465e-aa66-a75e736f3492.png)
![image](https://user-images.githubusercontent.com/55263191/216897584-05aebea4-65c8-46d6-bac1-af738ace4eb6.png)

2023-02-06 06:28 UTC, hahnbeelee commented
From Han:
> I could implement something but for practical purposes it will never go over 3 lines and almost always never 2 lines

2023-02-06 06:28 UTC, hahnbeelee approved these changes

2023-02-06 08:11 UTC, merged