WIP: Make github feedback links generate from mint.json
mintlify/mint pull request #306
Opened 2023-02-01 21:25 UTC by naz-mintlify

## Summary

## Test Plan

2023-02-01 21:29 UTC, hahnbeelee commented on client/src/types/config.ts
> +    path: string;
I think we briefly talked about this over a call, but make sure to set `isPrivate` too and if it is true, don't display the feedback buttons.

2023-02-01 21:57 UTC, naz-mintlify commented on client/src/types/config.ts
> +    path: string;
@hahnbeelee do we have isPrivate on the server as well in the `deployments.integration` collection?

2023-02-01 22:12 UTC, naz-mintlify commented on client/src/types/config.ts
> +    path: string;
I just added isPrivate

2023-02-01 22:39 UTC, tobias-mintlify requested changes

2023-02-01 22:39 UTC, tobias-mintlify commented on docs/mint.json
> +  "github": {
This is good for testing, but multitenant applications should inject this information from the server. The DB already has that information. You'll need to update the getStaticProps server endpoint and have it set `github` on mint.json  if it's not already set. That is, don't allow it to override anything the user specified in mint.json.

2023-02-01 22:41 UTC, naz-mintlify commented on docs/mint.json
> +  "github": {
I think I did that, should be a PR on the server. Would you like me to not hardcode mintlify values here?

2023-02-01 22:44 UTC, hahnbeelee commented on docs/mint.json
> +  "github": {
Looks like this has been done in the backend PR?

2023-02-01 22:48 UTC, naz-mintlify commented on docs/mint.json
> +  "github": {
Ah, yes. This was done on the backend. Let me revert and do it on client instead.

2023-02-01 22:49 UTC, naz-mintlify commented on docs/mint.json
> +  "github": {
@hahnbeelee Yes!

2023-02-01 22:55 UTC, tobias-mintlify approved these changes

2023-02-01 22:55 UTC, tobias-mintlify commented on client/src/ui/Feedback.tsx
> +      // TO DO: We should add the / at the end when not set, but gracefully handle when users
Please make a GitHub issue for this to do when you merge the PR

2023-02-01 23:01 UTC, hahnbeelee commented on docs/mint.json
> +  "github": {
@tobias-mintlify I think it's ok if we have it defined even though it's defined in our backend. Kinda like how it's defined in npm package.json's too. I haven't put a bunch of thought into it... Answering the question "Is there a benefit to defining the information in mint config even if they're using the Mintlify cloud version?

2023-02-01 23:02 UTC, hahnbeelee commented on docs/mint.json
> +    "path": "/",
I believe our DB uses "" for base path, not "/", but even then our docs don't live in the base path they live in "/docs"

2023-02-01 23:34 UTC, hahnbeelee commented on docs/mint.json
> +    "path": "/",
Oh wait actually, looking at our docs it looks like we dont precede it with a "/" so it would just be "docs"

2023-02-01 23:35 UTC, hahnbeelee commented on docs/mint.json
> +    "path": "/",
Thoughts on naming this "directory" instead? I know we use "path" everywhere, but I'm starting to feel like it is kinda generic/not super intuitive?

2023-02-01 23:48 UTC, tobias-mintlify commented on docs/mint.json
> +  "github": {
IMO users should only define if they want to override the DB settings

2023-02-01 23:49 UTC, tobias-mintlify commented on docs/mint.json
> +    "path": "/",
good catch! yea we don't need trailing slashes

2023-02-02 02:56 UTC, hahnbeelee requested changes

2023-02-02 02:56 UTC, hahnbeelee commented on client/src/types/config.ts
> +      isPrivate: boolean;
You're gonna have to make all of these values optional just because the configuration is user-defined and there's no guarantee that these fields will always exist.

2023-02-02 02:56 UTC, hahnbeelee commented on docs/mint.json
> +  "topbarLinks": [{
Can you change this so the formatting is back to how it was before? With the brackets on a different line?

2023-02-02 02:56 UTC, hahnbeelee commented on client/src/ui/Feedback.tsx
> +      {createSuggestHref && (
Since we're in the midst of editing this code, can you make the below svgs and components more modular by creating components for them with better names?

2023-02-02 02:56 UTC, hahnbeelee commented on client/src/ui/MDXContentController/PageHeader.tsx
> -          {subdomain && <UserFeedback />}
Can you link this PR to this issue so that when we merge it it closes this issue?

2023-02-02 02:56 UTC, hahnbeelee commented on docs/mint.json
> +}
Can you also add the newline again?

2023-02-02 02:56 UTC, hahnbeelee commented on client/src/ui/Feedback.tsx
> +    if (path && mintConfig?.repo?.github && !mintConfig.repo.github.isPrivate) {
Along with what I said of making all the properties inside the github property optional I think you're going to need to make this `mintConfig?.repo?.github?.isPrivate` for safety reasons of the property not existing

2023-02-02 02:56 UTC, hahnbeelee commented on client/src/ui/Feedback.tsx
> +      const { owner, repo, deployBranch, path: deploymentPath } = mintConfig.repo.github;
Same here. It's possible this spreading of props will fail if the user forgot to set these properties.

2023-02-02 02:56 UTC, hahnbeelee commented on client/src/ui/Feedback.tsx
> +        `https://github.com/${owner}/${repo}/edit/${deployBranch}/${urlPath}${removeFirstSlash(
Instead of appending a slash to urlPath and removing a slash from path, why don't we error handle for `urlPath` so that we can guarantee that all leading and following slashes are removed and do
`${urlPath}/${path}.mdx`?

2023-02-02 03:02 UTC, hahnbeelee commented on client/src/types/config.ts
> +      isPrivate: boolean;
And the default behavior would be to assume it's public

2023-02-02 03:05 UTC, hahnbeelee commented on client/src/ui/Feedback.tsx
> +        `https://github.com/${owner}/${repo}/edit/${deployBranch}/${urlPath}${removeFirstSlash(
Since `urlPath` is user-defined I think the easiest way to normalize slashes is to use the [path module](https://nodejs.org/api/path.html#pathnormalizepath)

2023-02-02 03:27 UTC, tobias-mintlify commented on client/src/ui/Feedback.tsx
> +      }
^ Could make the default `""` as well

2023-02-02 20:52 UTC, naz-mintlify commented on client/src/ui/Feedback.tsx
> +        `https://github.com/${owner}/${repo}/edit/${deployBranch}/${urlPath}${removeFirstSlash(
Correct me if I'm wrong, but this path module is on Nodejs and not in react. 

useCurrentPath() returns trailing slash in front always.

2023-02-02 20:59 UTC, tobias-mintlify commented on client/src/ui/Feedback.tsx
> +        `https://github.com/${owner}/${repo}/edit/${deployBranch}/${urlPath}${removeFirstSlash(
^ Nawaz is right, the path module won't work here.

2023-02-02 21:04 UTC, tobias-mintlify commented on client/src/types/config.ts
> +
please remove extra blank line

2023-02-02 21:06 UTC, hahnbeelee commented on client/src/ui/Feedback.tsx
> +        `https://github.com/${owner}/${repo}/edit/${deployBranch}/${urlPath}${removeFirstSlash(
Oh shoot you're right. I see the edge cases now.

2023-02-06 22:09 UTC, hahnbeelee approved these changes

2023-02-06 22:10 UTC, merged

2023-02-06 22:10 UTC, hahnbeelee commented
Closes #118