normalize z-index classes and fix stacking context
mintlify/mint pull request #322
Opened 2023-02-06 09:05 UTC by NicoZweifel

## Summary
Fixes the remaining z-index Issues (https://github.com/mintlify/components/issues/42) by ordering the StackingContext and seperating responsibilities of z-index classes like suggested in https://github.com/mintlify/components/pull/44#issuecomment-1407466150.

Information about how the StackingContext and z-index behaves can be found [here](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).
We don't have to remove `sticky`, but if creating a new StackingContext with `sticky`, it needs to have at least the same z-index if it is intended to display elements (tooltips) above, for example, the navbar.

I split the responsibilities of the zIndex Classes by adding this, which should help in the future with these kind of issues. 
```ts
export const zIndex = {
  Overlay: 'z-50',
  Popup: 'z-40',
  Navbar: 'z-30',
  SideBar: 'z-20',
  Control: 'z-10',
};
```

## Test Plan
Tested locally with the mint docs.

2023-02-06 17:06 UTC, tobias-mintlify requested changes
_Love_ the idea of making `ZIndex.ts` it'll make it much easier to maintain everything.

There is a bug where the nav bar is showing underneath the content though:

<img width="1410" alt="navbar" src="https://user-images.githubusercontent.com/110702161/217036316-bd1dd632-01e1-4122-9cd9-5b1b0e2cd1cb.png">

I checked the classes with inspect element and "z-30" was set but didn't have a class definition. Tailwind is not detecting the class. You should try changing the `ZIndex.ts` to a `.tsx` file so Tailwind will scan it. If that still doesn't work, add the classes to the allowlist in the Tailwind config.

Lastly, there were two or three other places with a z-10 and z-50 index we should switch to the ZIndex object. One of them was in the search bar code.

2023-02-06 17:06 UTC, tobias-mintlify commented on client/src/layouts/ZIndex.ts
> +export const zIndex = {
Tailwind may not be detecting these classes now that you moved them out of the React code. We usually need to add classes to `safelist` at the bottom of the Tailwind config when we programatically generate the class.

2023-02-07 05:33 UTC, NicoZweifel commented
Very good points, I'll improve the PR with the things you mentioned.

2023-02-07 08:37 UTC, NicoZweifel commented
Changing to .tsx did the trick.
I guess this also explains why it was working originally when I tested locally, probably the css was still cached in the browser.

I also improved the type inference and eslint warnings in MDXContentController a bit but the params and remaining types should probably be handled in a different issue.

Usually these warnings are fixable with [these](https://www.typescriptlang.org/docs/handbook/utility-types.html) and/or with generics.

2023-02-07 08:48 UTC, NicoZweifel commented on client/src/layouts/ZIndex.ts
> +export const zIndex = {
I changed the remaining z-index classes after searching in all files, they should all be normalized now.
Resolving for now, If adding it to the config is prefered over using a .tsx file, I could change the PR.

2023-02-07 17:56 UTC, tobias-mintlify approved these changes
Thank you this looks great! I tested and all code blocks with names and code groups are working correctly. I found a bug where code blocks without a file name have the same issue, but we likely just need to set the z-index in mintlify/components to fix this.

You can see code blocks without a file name here: http://localhost:3000/writing-content/code

<img width="96" alt="no file name" src="https://user-images.githubusercontent.com/110702161/217327076-49d07909-3ec5-475f-b01a-8c16f2c3267b.png">

2023-02-07 18:06 UTC, NicoZweifel commented
I checked and it seems to be because of  `absolute` and `z-10`  on the parent, creating a new StackingContext:
![image](https://user-images.githubusercontent.com/34443492/217329126-7939ce82-7bce-476d-932b-04158b39d2fe.png)

2023-02-07 18:09 UTC, merged