Address trivial errs for cli
mintlify/mint pull request #339
Opened 2023-02-08 23:21 UTC by hahnbeelee

## Summary
I didn't try to address everything because that would be very ambitious.
Before:
<img width="599" alt="image" src="https://user-images.githubusercontent.com/55263191/217674052-39ed6cff-b828-447c-83b8-854d7f501ff2.png">

After:
<img width="644" alt="image" src="https://user-images.githubusercontent.com/55263191/217673875-f5624d76-4422-4f8e-ac84-cbea4509b35e.png">

## Test Plan
* Look over code and make sure the logic is sound.
* Test basic CLI functionality

2023-02-08 23:23 UTC, tobias-mintlify commented on packages/mintlify/src/downloadImage.ts
> +  if (ext && !SUPPORTED_MEDIA_EXTENSIONS.includes(ext)) {
Maybe we can remove the `skipValidateImageExtension` check now that you added this?

2023-02-08 23:31 UTC, tobias-mintlify requested changes

2023-02-08 23:31 UTC, tobias-mintlify commented on packages/mintlify/src/scraping/detectFramework.ts
> +    docusaurusMeta.attr("content") === "Docusaurus"
All these checks have to be `.includes`, `===` is incorrect. The full string is of the form `Docusaurus v3.0.0-alpha.0`.

2023-02-08 23:31 UTC, tobias-mintlify commented on packages/mintlify/src/scraping/site-scrapers/scrapeDocusaurusSection.ts
> +    downloadLogoImage(logoSrc, imageBaseDir, origin, overwrite);
`downloadLogoImage` already exits without downloading if logoSrc is missing. I'd prefer to keep it the way we had it to avoid duplicate if-statements in every scraper implementation.

2023-02-08 23:31 UTC, tobias-mintlify commented on packages/mintlify/src/util.ts
> +    } catch (e: any) {
You don't need to set a type when catching things in Typescript. In fact, the only types it would set let you set are `any` and `unknown`. Keeping the default seems better than disabling all type checking

2023-02-08 23:31 UTC, hahnbeelee commented on packages/mintlify/src/downloadImage.ts
> +  if (ext && !SUPPORTED_MEDIA_EXTENSIONS.includes(ext)) {
What was the reasoning for adding it in the first place? I see [the PR](https://github.com/mintlify/mint/pull/284) Does intercom not have extensions?

2023-02-08 23:32 UTC, tobias-mintlify commented on packages/mintlify/src/downloadImage.ts
> +  if (ext && !SUPPORTED_MEDIA_EXTENSIONS.includes(ext)) {
Yeah Intercom doesn't have extensions so the `SUPPORTED_MEDIA_EXTENSIONS.includes` check fails. Your `ext &&` addition to this if-statement addresses the issue in a simpler way.

2023-02-09 01:00 UTC, hahnbeelee commented on packages/mintlify/src/scraping/site-scrapers/scrapeDocusaurusSection.ts
> +    downloadLogoImage(logoSrc, imageBaseDir, origin, overwrite);
The beauty of typescript is that we don't have to do `string | undefined` as inputs for functions. Sometimes it's ok to add if guards if it means that the logic is more clear to follow.

2023-02-09 06:56 UTC, tobias-mintlify commented on packages/mintlify/src/scraping/site-scrapers/scrapeDocusaurusSection.ts
> +    downloadLogoImage(logoSrc, imageBaseDir, origin, overwrite);
In that case, you need to update the if-statements to do the full check: `if (!isValidImageSrc(imageSrc))`

2023-02-09 17:22 UTC, tobias-mintlify requested changes

2023-02-09 17:22 UTC, tobias-mintlify commented on packages/mintlify/src/scraping/downloadAllImages.ts
> +      if (imageSrc || !isValidImageSrc(imageSrc)) {
This is going to exit whenever we have a valid image source. Are you missing a `!`?

2023-02-09 17:24 UTC, hahnbeelee commented on packages/mintlify/src/scraping/downloadAllImages.ts
> +      if (imageSrc || !isValidImageSrc(imageSrc)) {
omg good catch

2023-02-09 17:53 UTC, hahnbeelee commented on packages/mintlify/src/scraping/site-scrapers/scrapeDocusaurusSection.ts
> +    downloadLogoImage(logoSrc, imageBaseDir, origin, overwrite);
I just changed it to `string | undefined` for now cuz I think it's really subjective. What looks repetitive to you might look cleaner to me etc. but it's really just a small stylistic difference. If I made it so it just took `string` and not `string | undefined`, then `if (isValidImageSrc(imageSrc))` would yell because `imageSrc` would be type `string | undefined`. I think what I have now is good because it's the middle ground of what you were suggesting and what I had originally. There's like 3 layers of this prop being passed down to `isValidImageSrc` and in the second layer we check if it's defined or not which allows us to reduce the amount of repeated code. :3

2023-02-09 17:55 UTC, tobias-mintlify approved these changes

2023-02-09 17:55 UTC, hahnbeelee commented on packages/mintlify/src/downloadImage.ts
> -    return false;
u right. I wasn't thinking.
Since the type is `string`, `undefined` will never be passed to this function so we no longer have to check for `undefined`. However I didn't think about the falsy value  `""`.
For functions that take in arrays we actually shouldn't be checking for `Array.isArray` because if you type it as an array you're allowed to assume it's an array. A check for `arr.length > 0` is good though.

2023-02-09 18:43 UTC, merged