create useMdxContentController hook
mintlify/mint pull request #359
Opened 2023-02-13 13:04 UTC by NicoZweifel

## Summary
When I first started working on mint I found it a bit hard to read the MDXContentController because of a lot of `any` usage and state, context, utilities and UI mixed in the same file.

This PR moves state, hooks and utility functions into seperate files and makes it possible to extend the existing context or add something like MDXContentController context to seperate the component without having to pass props.

- Could add MDXContentController context and a reducer, split components and then it could look similar to this:
```tsx
const [state,dispatch] = useMDXContentController(props);
return (
<MDXContentController value={[state,dispatch]}>
  <MDXContentControllerHeader />
  <MDXContentControllerContent />
  <MDXContentControllerFooter />
  <MDXContentControllerSideBar />
<MDXContentController />
);
```
- Children could also have a hook to access MDXContent context like this:
```tsx
const [state] = useMDXContent();
```

I think this would be much cleaner and help new contributors in getting familiar with the MDXContentController and help overall with improving types, testing possibilities and reduce eslint warnings.

## Test Plan

Draft PR for now, could add extra tests for new isolated functions.

2023-02-13 14:40 UTC, NicoZweifel commented
Added some more changes to demonstrate, could also add a reducer to simplify the state in useMDXContentController.

2023-02-13 18:19 UTC, tobias-mintlify commented
I'm loving this. 🥇 Let me know if you need any help I'm excited to ship this refactor

2023-02-13 19:07 UTC, NicoZweifel commented
I think this is now in it's final stages, I just added a reducer and some more hooks + dispatches with dependencies.
This should reduce the amount of re-renders that are triggered.
I did not add reducer functions for every field but there is a dispatch to update the whole state with a Partial type.

I will test some more and possibly add some tests for the state/hooks.

2023-02-13 19:27 UTC, NicoZweifel commented
@tobias-mintlify Would be happy to have another set of eyes to take a look and make some suggestions/improvements.

We could always move more stuff out of `UseMDXContentController` into seperate hooks/files but I think with ~100 lines it's fine.

Other than that I think it is worth it to improve some of the types to remove some of the `any` occurrences, but I think this should probably be done in a seperate PR.

2023-02-13 19:45 UTC, NicoZweifel commented
Naming could also be improved probably, for example I was thinking of renaming `useGeneratedRequestExamples` to a more generic `useContentApi` or something similar, since it also updates the `api` and another field. (maybe `useRequestApi`).

2023-02-13 20:55 UTC, tobias-mintlify reviewed
I tested this on a few things and its all functional. 🥳  I'll ask the others to review too when you mark it as ready.

I have a few comments, not related to this PR but things you should be aware of when refactoring:

1. We want apiBaseIndex to be stored while the user navigates between pages. We can keep it like we have right now, but we'll need to load it from localstorage at some point.
2. We want API authentication inputs to be stored between pages. These are slightly more sensitive so localstorage may not be appropriate. It looks to me like this refactor will make it easier to store the authentication values in `state` so we can build this feature.
3. We want to expand Mintlify to power other types of communication like blogs and changelogs. (You've probably seen some WIP blog code). This will likely require us to customize the navigation on the left based on the page mode. This PR looks easier to maintain long-term, just take care we are not locking ourselves in to something that will be hard to customize for other use cases. Having skimmed the PR, I think it's good and any improvements like I'm mentioning can probably be a follow up refactor.
4. Can you write a `contributing.mdx` explaining the dispatch architecture you've added here? If you put it in the `docs` folder it'll show up as a hidden page at `mintlify.com/docs/contributing`. Hidden pages don't show up in the navigation but are available when linked to directly. We'll keep it hidden until we publish the self-hosting docs we're writing.

2023-02-13 21:24 UTC, NicoZweifel commented
1. We could add a context + provider to _app.tsx. It is a really convenient way of keeping state between pages in nextjs.
   One thing to keep in mind tho is that next 13 is adapting a new folder structure ([appDir)](https://beta.nextjs.org/docs/routing/pages-and-layouts)  where state between pages is not shared in `app.tsx` anymore but in shared layouts, which would require to move the providers there when adapting the new structure.

2. For Authentication, the same as above applies, although might wanna use a database session or if it is desired to keep authentication between different pages/subdomains, a JWT or cookie might be required.
I am not sure how the authentication works at the moment but [`next-auth`](https://next-auth.js.org/) is super useful when it comes to any form of authentication with next.

3. Yea I saw some of the WIP Blog Code and was wondering about if it is supposed to be SideContent but figured it should be because of the `!isWideSize` check.

4. I will add some comments and documentation tomorrow and mark the PR as ready afterwards 👍

2023-02-13 21:34 UTC, tobias-mintlify commented
Regarding `_app.tsx`, we can't add context providers there because multitenant hosting needs to have different values for each "site". Putting context in `SupremePageLayout` should have the intended effect without causing issues.

2023-02-14 02:43 UTC, NicoZweifel commented on client/src/ui/MDXContentController/Api.tsx
> +  const setApiBaseIndex = useCallback(
Could also remove the props of  `ApiPlayground` , use 
```tsx 
const [state] = useMDXContent()
``` 
in  `ApiPlayground`  and move these callbacks to `ApiPlayground` .

2023-02-14 02:45 UTC, NicoZweifel commented on client/src/ui/MDXContentController/Header.tsx
> +    <BlogHeader pageMetadata={pageMetadata} />
Could also do the same here (remove props, use context in child).

2023-02-14 02:46 UTC, NicoZweifel commented on client/src/ui/MDXContentController/SidePanel.tsx
> +      <TableOfContents
Could remove the props and use context in children here as well

2023-02-14 02:50 UTC, NicoZweifel commented on client/src/ui/MDXContentController/Api.tsx
> +  const setApiBaseIndex = useCallback(
for example like [this](https://github.com/NicoZweifel/mint/blob/remove-props/use-context/client/src/ui/ApiPlayground.tsx):
```tsx
export function ApiPlayground() {
  const { basePath } = useRouter();
  const { mintConfig, openApiFiles } = useContext(ConfigContext);
  const [apiBaseIndex, setApiBaseIndex] = useState(0);

  const [{ openApiPlaygroundProps, pageMetadata, api, paramGroups }] = useMDXContent();

  const contentType = openApiPlaygroundProps.contentType ?? pageMetadata.contentType;

  const onApiBaseIndexChange = useSetApiBaseIndexCallback();
  const onInputDataChange = useSetApiPlaygroundInputsCallback();
...
```

2023-02-15 01:35 UTC, tobias-mintlify reviewed
Tested again and everything looked good. 🚀 I'll wait for some of the others to review before approving since it's a big change.

2023-02-15 07:01 UTC, NicoZweifel commented
I added some docs in docs/code/MDXContentController and linked to them from contributing.mdx.
If another structure is preferred, I can change it accordingly.

Would also be eager to hear your opinions about removing props from `SidePanel`, `Header` and `ApiPlayground` and using the context instead.
For example like [here](https://github.com/NicoZweifel/mint/pull/1).

It'd be great to get another review.
I don't feel 100% satisfied with the MDXContentController  docs at the moment (I'd like to use less CodeBlocks/Code for maintenance reasons but still be able to show some concepts.

Feel free to make suggestions.

2023-02-15 07:36 UTC, benjamin-shen reviewed
Impressive PR 🥇, thank you so much!! This refactor makes a lot of sense to me.

2023-02-15 07:36 UTC, benjamin-shen commented on client/src/context/MDXContentContext.tsx
> +    case MDXContentActionEnum.SET_API_PLAYGROUND:
I think `SET_USER_DEFINED_EXAMPLES`...`SET_API_PLAYGROUND` should be stricter on which properties in state are updated, and be in their own case statements.

For example, here is what I would change one of the actions to:
```tsx
case MDXContentActionEnum.SET_USER_DEFINED_EXAMPLES:
  const { requestExample, responseExample } = action.payload;
  return {
    ...state,
    requestExample,
    responseExample,
  };
```

If we don't do this, then we can pass `isApi` (or `isBlogMode`, etc) as an object in the payload so that we can update the state in the same way:
```tsx
dispatch({
  type: MDXContentActionEnum.SET_IS_API,
  payload: { isApi },
});
```
instead of how it's currently done:
```tsx
dispatch({
  type: MDXContentActionEnum.SET_IS_API,
  payload: isApi,
});
```

But then, there is not really a point to distinguishing different actions, and we might as well use `useState` instead of `useReducer`. Of course, I think `useReducer` makes a lot of sense.

Did that make sense? Btw, if this was just a one-to-one mapping of the existing functionality, then I think it can also be cleaned up in another PR. This diff is plenty large 😋

2023-02-15 07:36 UTC, benjamin-shen commented on client/src/context/MDXContentContext.tsx
> +const initialState = {
Can you define a type for this?

2023-02-15 07:36 UTC, benjamin-shen commented on client/src/ui/MDXContentController/Footer.tsx
> +              href={previous?.href as never}
Learning question: why `as never`?

2023-02-15 08:04 UTC, NicoZweifel commented on client/src/context/MDXContentContext.tsx
> +    case MDXContentActionEnum.SET_API_PLAYGROUND:
Thanks for your input 👍 

Yea, I agree, that makes a lot of sense and I was thinking about these things in similar ways.

>For example, here is what I would change one of the actions to:

I wish there was an easier way to purge the properties in typescript when assigning a type but I don't think there is without using some external frameworks/libraries.

I can implement it with destructuring for `SET_USER_DEFINED_EXAMPLES` and `SET_API_PLAYGROUND`.

>But then, there is not really a point to distinguishing different actions, and we might as well use useState instead of useReducer. Of course, I prefer useReducer.

Yea I think it makes more sense to take advantage of beeing able to change the types for the dispatch function, since the arguments are also typed anyway.
`{ isApi }` instead of `isApi` seems to just be extra braces.

>This diff is plenty large
Yea I was trying not to change to much existing components and logic, especially  `SidePanel`, `Header` and `ApiPlayground` could still be improved a bit. I think we should keep that to seperate PR's tho.

I'll add the suggested change.

2023-02-15 08:08 UTC, NicoZweifel commented on client/src/context/MDXContentContext.tsx
> +const initialState = {
Oh yea, nice catch 👍 , I'll add the type definition to the declaration.

2023-02-15 08:18 UTC, benjamin-shen commented
> Would also be eager to hear your opinions about removing props from SidePanel, Header and ApiPlayground and using the context instead.

Since the context is serving as a shared/global store, my thought is that anything that we would normally put in a global store we should put in the context. So definitely not all props should be removed, just the ones that may be used across components horizontally. Specifically in the case of Api => ApiPlayground (in the demo PR), it feels more like normal vertical sharing. It definitely looks cleaner! But I'm not sure there is much benefit other than that. What are your thoughts?

Also, I was wondering why you went with this route instead of Redux and it looks like the Context API is [a lot better for our use case](https://dev.to/ruppysuppy/redux-vs-context-api-when-to-use-them-4k3p) (static data, smaller bundle size). I'm very happy you went this direction 😄

2023-02-15 08:21 UTC, NicoZweifel commented on client/src/ui/MDXContentController/Footer.tsx
> +              href={previous?.href as never}
[This ](https://blog.logrocket.com/when-to-use-never-and-unknown-in-typescript-5e4d6c5799ad/)is a pretty nice post about `never` and `unknown`.


In this case it's just an alternative to `any` , that doesnt cause an error or eslint warning.
I used `never` because it got suggested by eslint, resolved eslint warnings.
It *should* never happen that href is undefined.

The Issue comes from `<Link>` requiring href of Type `Url`, but `previous.href` and `next.href` could be `string | undefined`.

Note that something like this would also work:
```tsx
{previous?.href && (
  <Link
    href={new URL(previous?.href)}
```
But I didn't want to make any additonal changes that could affect the logic of the component render inside of this PR.

2023-02-15 08:23 UTC, benjamin-shen commented on client/src/ui/MDXContentController/Footer.tsx
> +              href={previous?.href as never}
Gotcha, very interesting!

2023-02-15 08:26 UTC, NicoZweifel commented on client/src/ui/MDXContentController/Footer.tsx
> +              href={previous?.href as never}
the docs seem to have been depcrecated, [link ](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#the-never-type) to new docs

2023-02-15 08:43 UTC, NicoZweifel commented
> Also, I was wondering why you went with this route instead of Redux and it looks like the Context API is [a lot better for our use case](https://dev.to/ruppysuppy/redux-vs-context-api-when-to-use-them-4k3p) (static data, smaller bundle size)

Yea I agree, it is better for most use-cases I feel like nowadays.

Disadvantages like having state and ui in the same file don't really count as you can write custom hooks to encapsulate that.
With lots of dynamic data it also gets more interesting and a reducer and hook to encapsulate state becomes mandatory imo.

These issues are already covered tho with `useMDXContentController`, `useReducer` and the action types.

It basically comes down to a tradeoff:
-  Use redux, to potentially save code and time when you have a lot of complex different states all over the place.
This will require everybody to learn redux eventually and increases bundle size. 
-  Use your own reducers/context/hooks/architecture.

I feel like the tools, docs and general knowledge of the context api are getting better and better and there is less and less reason to use redux as time goes on.

2023-02-15 09:00 UTC, NicoZweifel commented on client/src/context/MDXContentContext.tsx
> +    case MDXContentActionEnum.SET_API_PLAYGROUND:
Updated with suggested change.

2023-02-15 12:29 UTC, NicoZweifel commented on client/src/hooks/useTableOfContents.ts
> +  const registerHeading = useCallback((id: string, top: number) => {
Yea, I think so, as far as i remember it was complaining after extracting type definitions, that types don't match 😋

2023-02-15 12:54 UTC, NicoZweifel commented on client/src/context/MDXContentContext.tsx
> +const initialState = {
Updated with suggested change.

2023-02-15 13:06 UTC, NicoZweifel commented
@tobias-mintlify 
@benjamin-shen 
> Since the context is serving as a shared/global store, my thought is that anything that we would normally put in a global store we should put in the context. So definitely not all props should be removed, just the ones that may be used across components horizontally. Specifically in the case of Api => ApiPlayground (in the demo PR), it feels more like normal vertical sharing. It definitely looks cleaner! But I'm not sure there is much benefit other than that. What are your thoughts?

I agree about about props and not putting extra things in the context.
The context should only contain the state that is used for `MDXContentController`.

I improved the docs some more and closed the PR with `ApiPlayground`.

We could remove more props, and use the new context, like in `ApiPlayground`, specifically `SidePanel` and `Header`.
But I will leave it as is for now because it will get too large otherwise.

Thanks for your considerations, I think this is now good to go 🚀

2023-02-15 20:03 UTC, benjamin-shen reviewed
A few doc nits

2023-02-15 20:03 UTC, benjamin-shen commented on docs/code/mdx-content-controller.mdx
> +    }
```suggestion
    switch (type) {
        case MDXContentActionEnum.SET_STATE:
            return {
            ...state,
            ...action.payload,
        };
        // other cases
        ...
    }
```

2023-02-15 22:52 UTC, hahnbeelee requested changes
The footer doesn't have enough padding.
This branch:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/55263191/219206619-6df71140-6cf7-47ad-8a1e-ebca3b0cd120.png">
Production:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/55263191/219206963-8e689407-77f5-4ea4-a2b1-238e99128810.png">

2023-02-15 23:00 UTC, tobias-mintlify commented
I'm very impressed there was only one bug found 🚀

2023-02-15 23:07 UTC, tobias-mintlify commented
@hahnbeelee looks like this bug is unrelated to the PR, you can see the padding is messed up on [this page already](https://mintlify.com/docs/api-playground/demo). Looks like it's caused by API Playground pages. I'll look into fixing it but we can merge this in if that's the only bug you found.

2023-02-15 23:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mintlify/mint?pullRequest=359) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mintlify/mint?pullRequest=359) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: NicoZweifel<br/>:x: tobias-mintlify<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mintlify/mint?pullRequest=359) it.</sub>

2023-02-15 23:16 UTC, tobias-mintlify commented
I pushed a fix for the padding even tho it's unrelated to the PR.

2023-02-16 00:57 UTC, hahnbeelee approved these changes
Honestly haven't been able to test very in-depth because of how large this is - I wonder if there's a way for if we could've broken this refactor down. But overall, thank you so much for your work! I really really appreciate it. I can't wait to work off of this code :)

2023-02-16 00:57 UTC, hahnbeelee commented on client/src/ui/MDXContentController/SidePanel.tsx
> +export const SidePanel = () => {
Can we specify what side the `SidePanel` is on?

2023-02-16 00:57 UTC, hahnbeelee commented on client/src/ui/MDXContentController/SidePanel.tsx
> +export const SidePanel = () => {
Maybe we should also rename `ContentSideLayout.tsx` it has always bothered me becuase it isn't clear which side it is.

2023-02-16 02:08 UTC, tobias-mintlify commented
Han added a CLA bot this morning that blocks deploys, I'll merge after Nico signs.

2023-02-16 03:21 UTC, hanywang2 approved these changes

2023-02-16 03:25 UTC, tobias-mintlify approved these changes

2023-02-16 03:26 UTC, benjamin-shen approved these changes

2023-02-16 08:37 UTC, NicoZweifel commented on client/src/ui/MDXContentController/SidePanel.tsx
> +export const SidePanel = () => {
Yea I agree that it was quite large and that it might be a bit hard to quickly wrap your head around the changes.

I tried to keep it to splitting state and the MDXContentController component for this PR
I am sorry if it was hard to get an overview.

The docs hopefully help a bit with that and understanding the concepts and changes.

> Can we specify what side the SidePanel is on?

We could change `SidePanel` and `ContentSideLayout` to have an `anchor` or `side` prop with `left | right` as type.

> Maybe we should also rename ContentSideLayout.tsx it has always bothered me becuase it isn't clear which side it is.

Yea, i think so too.
Renaming it or adding an `anchor` or `side` seem both good options.

2023-02-16 14:09 UTC, NicoZweifel commented on docs/code/mdx-content-controller.mdx
> +    );
I formatted the doc files with prettier and pushed the changes.

2023-02-16 17:01 UTC, merged