Use PostHog internal analytics setup
mintlify/mint pull request #417
Opened 2023-02-22 20:26 UTC by hanywang2

## Summary

This PR swaps out Segment for Posthog on internal analytics

## Test Plan
- No build errors
- Meant to be test in prod with proper configs

2023-02-22 20:42 UTC, hahnbeelee requested changes

2023-02-22 20:42 UTC, hahnbeelee commented on client/src/analytics/implementations/posthog.ts
> +  subdomain?: string;
The fact that we had to add the `subdomain` property for post hog because we're using it internally and remove it from segment because we aren't using it internally seems like bad practice.
Analytics should be generalized and it's weird that we're editing them for our own purposes. At the least we should create a new class `InternalPostHogAnalytics` that extends `PostHogAnalytics`. We will most likely be refactoring analytics (given some of the eslint errors) so we can hold off on doing this for now.

2023-02-22 20:42 UTC, hahnbeelee commented on client/src/analytics/implementations/posthog.ts
> +  subdomain?: string;
Can you add a comment about it being for internal purposes or create the new internal object type?

2023-02-22 20:42 UTC, hahnbeelee commented on client/src/analytics/internal/index.ts
> +export default class InternalAnalytics extends PostHogAnalytics {
Wait I made that comment before I saw this. You should def be editing this so that subdomain is a property here. Lmk if im wrong though/if this is difficult.

2023-02-23 02:21 UTC, hanywang2 commented on client/src/analytics/implementations/posthog.ts
> +  subdomain?: string;
Added a comment, but If you look at the way analytics is orchestrated, create eventListener creates a function and returns that. This means that the event data that actually needs to be sent is actually passed as a param within that function, meaning that you need the subdomain by that point. It's hard to explain, but tl;dr idk how else to do it

2023-02-23 02:23 UTC, hahnbeelee approved these changes
We will refactor this in the future

2023-02-23 02:25 UTC, merged