Previewing tsc, add prettier/format to previewing
mintlify/mint pull request #433
Opened 2023-02-28 14:56 UTC by NicoZweifel

## Summary
 I used this to fix the build errors in `previewing` https://github.com/mintlify/mint/issues/432

## Test Plan
Able to build `previewing` with these changes.

2023-02-28 19:22 UTC, hahnbeelee requested changes
Ah apologies about the annoying build errors. Ben and I recently refactored the package structure for the CLI and when we ran it we swore it worked but I think it was a fluke.

Since this is also a recent refactor I'm not sure what the best way to test it is. I just went into `dist/local-preview/index.js` and commented  `await dev();` and navigated to our docs & ran the file (`cd ../../docs && node ../packages/mintlify-previewing/dist/local-preview/index.js`) but I got an error saying `Cannot read properties of undefined (reading 'port')`. Can you fix that too?

![CleanShot 2023-02-28 at 11 19 26](https://user-images.githubusercontent.com/55263191/221956781-30898d46-459b-4164-b5c9-53c7ac43dd5e.png)

I think it's line 155 at `src/local-preview/index.ts`

2023-02-28 22:15 UTC, NicoZweifel commented
> Ah apologies about the annoying build errors. Ben and I recently refactored the package structure for the CLI and when we ran it we swore it worked but I think it was a fluke.

Haha no problem, it probably didn't show because of local build files or sth.

> I think it's line 155 at src/local-preview/index.ts

I'll check but It was building fine for me with these changes. 
I was commenting dev and then using `node bin/index.js dev
` to test 😄. I was considering writing a test for a bit but was not sure if it was worth it yet since it would require quite a bit of mocking I guess.

2023-02-28 22:20 UTC, NicoZweifel commented
> I think it's line 155 at `src/local-preview/index.ts`

I changed to use optional chaining (?)
```ts
argv?.port as string
```

2023-03-01 01:04 UTC, hahnbeelee approved these changes

2023-03-01 01:51 UTC, merged