[1/x] Add Initial Blog Mode
mintlify/mint pull request #82
Opened 2022-11-29 23:08 UTC by hanywang2

# Summary

The below only are in effect if `mode: "true"`

<img width="1440" alt="Screen Shot 2022-11-29 at 3 07 54 PM" src="https://user-images.githubusercontent.com/44352119/204668176-6dd45bed-d8e6-438b-a99d-0174e8eadfa3.png">
<img width="1440" alt="Screen Shot 2022-11-29 at 3 07 45 PM" src="https://user-images.githubusercontent.com/44352119/204668185-21174e6b-9909-41cd-9811-cf2f46a58371.png">

# Test Plan

- Simple code glance
- Check screenshot looks good

2022-11-29 23:36 UTC, hahnbeelee commented on client/src/ui/Blog.tsx
> +export function BlogSidebar() {
Also confused between the difference between BlogNav and BlogSidebar

2022-11-29 23:37 UTC, hahnbeelee commented on client/src/ui/MDXContentController/MDXContentController.tsx
> +  const isBlogMode = meta.mode === 'blog';
Add question mark: `meta?.mode`

2022-11-29 23:38 UTC, hahnbeelee commented on client/src/ui/MDXContentController/PageHeader.tsx
> +  const title = meta.title || slugToTitle(currentPath)
makes sense moving this logic here 👍

2022-11-29 23:43 UTC, tobias-mintlify requested changes

2022-11-29 23:43 UTC, tobias-mintlify commented on client/package.json
> +    "date-and-time": "^2.4.1",
Can you write tickets for how we will allow customizing the time zone. Right now I assume everything is using GMT which will slightly shift dates for some customers.

2022-11-29 23:43 UTC, tobias-mintlify commented on client/src/ui/MDXContentController/PageHeader.tsx
> +            !isBlogMode && <UserFeedback />
Please refactor this before it gets messy. We'll likely add other modes in the future and these if-flags will be hard to refactor later.

The entire blog variable should not exist in this component.

I would suggest taking UserFeedback and Date as props. You can dynamically choose to pass them in based on whether the blog property exists outside this component.

2022-11-29 23:43 UTC, tobias-mintlify commented on client/src/ui/MDXContentController/PageHeader.tsx
> +        isBlogMode && <div className="mt-4 flex space-x-5">
I like this better on the right now that we have other buttons there.

2022-11-29 23:43 UTC, tobias-mintlify commented on client/src/ui/Blog.tsx
> +export function BlogSidebar() {
Here is where I'd move the authors.

2022-11-29 23:43 UTC, tobias-mintlify commented on client/src/types/metadata.ts
> +  _context?: {
Remember to delete this when we move the values into `metadata`

2022-11-29 23:43 UTC, tobias-mintlify commented on client/src/ui/MDXContentController/TableOfContents.tsx
> +    return <BlogSidebar />
Please move this to MDXContentController by adding an if-branch in this if-statement:

```
{!isWideSize &&
        (isApi || requestExample || responseExample ? (
          <ContentSideLayout sticky>
```

2022-11-29 23:46 UTC, hahnbeelee approved these changes
I'm mainly confused by the naming conventions of some of these files, but I guess it doesn't really matter because the UI is all going to be abstracted away into mintlify/components anyway.

The UI looks good. I still think the "Join" button on the right needs to not be so dark in light mode.

![image](https://user-images.githubusercontent.com/55263191/204673020-4b0bee24-eb65-4a5d-996e-eb919bd2e433.png)

2022-11-29 23:47 UTC, hahnbeelee commented on client/src/types/MDXContentControllerTypes.ts
> -export type Meta = {
Also i think we should keep all types in the types folder. Even though it may seem like we're only using it in 1 files, it snowballs really fast once another location does need the type :/ I think it's better practice this way.

2022-11-30 02:58 UTC, hanywang2 commented on client/src/ui/Blog.tsx
> +export function BlogSidebar() {
Fair enough on the difference. Renaming

2022-11-30 03:02 UTC, hanywang2 commented on client/package.json
> +    "date-and-time": "^2.4.1",
Great question. Awhile back I built this scheduling app that had to deal with timezones and schedules. So if you actually create the date object (`new Date()`) on the client, the timezones are accounted for. The data object in this case is built on the client, and then used for date-and-time, so it will always be localized

2022-11-30 03:08 UTC, hanywang2 commented on client/src/ui/MDXContentController/PageHeader.tsx
> +        isBlogMode && <div className="mt-4 flex space-x-5">
My thoughts on why it's not on the right now:
- The goal is to keep the right-side as empty as possible because we want to optimize for people to read the content with as few distractions as possible
- The authors aren't as important to be constantly viewed (probably why Stripe made it go away even though they easily could've kept it there with absolute position https://stripe.com/blog/new-and-improved-stripe-terminal). I personally have the preference that the author should only be acknowledged, but not reminded cause it doesn't matter that much
- I compared it side-by-side, and on the main page feels better to me (hard to explain)

2022-11-30 03:39 UTC, merged